from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="bitcoin_trading_rl",
    version="1.0.0",
    author="Kim, Sungwoo",
    author_email="rkwk0112@gmail.com",
    description="A comprehensive cryptocurrency trading framework using reinforcement learning and advanced trading strategies",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/cd80/don.git",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Office/Business :: Financial :: Investment",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.19.0",
        "pandas>=1.2.0",
        "torch>=1.8.0",
        "scikit-learn>=0.24.0",
        "scipy>=1.6.0",
        "statsmodels>=0.12.0",
        "ccxt>=1.50.0",
        "aiohttp>=3.7.0",
        "python-binance>=1.0.0",
        "ta>=0.7.0",
        "tensorflow>=2.4.0",
        "gym>=0.18.0",
        "stable-baselines3>=1.0",
        "optuna>=2.6.0",
        "wandb>=0.10.0",
        "pytest>=6.2.0",
        "black>=21.5b2",
        "flake8>=3.9.0",
        "mypy>=0.812",
        "pytest-cov>=2.12.0",
        "pytest-asyncio>=0.15.0",
        "pre-commit>=2.13.0",
    ],
    extras_require={
        "dev": [
            "black",
            "flake8",
            "mypy",
            "pytest",
            "pytest-cov",
            "pytest-asyncio",
            "pre-commit",
        ],
        "docs": [
            "mkdocs",
            "mkdocs-material",
            "mkdocstrings",
            "mkdocs-git-revision-date-localized-plugin",
            "mkdocs-minify-plugin",
        ],
    },
    entry_points={
        "console_scripts": [
            "bitcoin_trading_rl=src.main:main",
            "update_status=scripts.update_status:main",
        ],
    },
    project_urls={
        "Bug Reports": "https://github.com/cd80/don/issues",
        "Source": "https://github.com/cd80/don",
    },
)
